# Generated by Django 3.0.1 on 2020-01-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('select', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
